# Experiment 0 Documentation
metadata:
  created_date: "2024-03-19"
  author: "kag"
  status: "in_progress"

description: |
  Initial experiment to establish baseline study dataset and modeling approach.
  This will serve as a template for future experiments.

important_notes: |
  WARNING - Hour Numbering:
  ERCOT and Python use different hour numbering conventions:
  - ERCOT: Uses 1-24 (where hour 24 is midnight)
  - Python datetime: Uses 0-23 (where hour 0 is midnight)
  
  This difference is handled in our ETL process (see ERCOTBaseETL.combine_date_hour),
  but it's crucial to be aware of this when:
  - Analyzing raw ERCOT data
  - Converting between ERCOT and Python time representations
  - Interpreting visualizations or results
  - Implementing new data processing functions

data_sources:
  - processed_dam_spp_clean
  - processed_dam_system_lambda_clean
  - processed_load_clean
  - processed_wind_clean
  - processed_solar_clean
  - processed_rt_spp_transformed  # Contains hourly statistics

workflow_steps:
  study_dataset: "03-kag-exp0-study-dataset.py"
  model_train: "04-kag-exp0-model-train.py"
  model_inference: "05-kag-exp0-model-inference.py"

key_decisions:
  - Two-stage data processing (clean → transform) for better auditability
  - RT SPP uses transformed data with hourly statistics, others use cleaned data
  - Consistent naming across clients (location, price, dst_flag)

findings: []
next_steps: 
  - Implement feature creation logic in study dataset
  - Verify hourly statistics calculations
  - Define target variables for modeling 